### ISSUE TITLE
Bot keeps spamming Rock Paper Scissors in DMs, without any games on!

### ISSUE THREAD

**Issue by vladfrangu** [hedgehog1029/nekomare#1]
So, I think this might sound stupid, but I managed to break the bot..

In a server I'm in, I've ran "neko help", I've got the DM of the commands, followed by a constant spam of "Choose either rock, paper or scissors.". The bot won't stop by running "neko rps cancel", as theres not a game running right now. Heres a [GIF](http://i.imgur.com/a8JMwwt.gifv). (Sorry for potato quality).

Anything I should do? I know I can block the bot but still..

**Comment by hedgehog1029** [comment]
If the bot's still spamming you I would suggest blocking it until I can get this fixed. I've had a problem like this before, but I'm sure I fixed it.

**Comment by hedgehog1029** [comment]
I've restarted the bot and I'm investigating the cause now. Come join us in the [Foam Robot Discord](https://discord.gg/eRe4Uqg) for updates, support, and quick responses to issues!
